#! /usr/bin/python3

# Google Translate Unofficial
#
# Copyright 2020 Ramazan Emre Osmanoglu <ramazanemreosmanoglu@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later



import gi

gi.require_version('Gtk', '3.0')

from gi.repository import Gtk

try:
    from googletrans import Translator
except ImportError:
    print(
        'This application needs googletrans module\n'
        'For install:\n'
        '   sudo apt install python3-pip\n'
        '   pip3 install googletrans'
    )

    exit()

translator = Translator()

class Handler:
    def translate_clicked(self, button):

        href = from_text_buffer.get_text(from_text_buffer.get_start_iter(), from_text_buffer.get_end_iter(), True)

        if not href:
            code = error_message.run()
            if code == -7:
                error_message.hide()
            return
        
        fromc = fromcode.get_text()
        if not fromc:
            fromc = 'auto'
        
        to_c = tocode.get_text()
        if not to_c:
            code = connection_error.run()
            if code == -7:
                connection_error.hide()
            return
        
        try:
            result = translator.translate(href, dest=to_c, src=fromc)
        except:

            code = connection_error.run()
            if code == -7:
                connection_error.hide()
        else:
            result_buffer.set_text(result.text)
        
        
    def open_about(self, *args):
        x = about.run()
        if x == -4:
            about.hide()
        
    
    def close_window(self, window):
        Gtk.main_quit()
    


builder = Gtk.Builder()
builder.add_from_file('googletranslateunofficial/translate.glade')
builder.connect_signals(Handler())

_ = builder.get_object

window = _('main_window')
about = _('about_window')
result_buffer = _('result-text-buffer')
fromtext = _('from_text')
translate_b = _('translate')
from_text_buffer = _('from-text-buffer')
fromcode = _('from')
tocode = _('to')
error_message = _('error-message')
connection_error = _('connection-error')

window.show_all()

Gtk.main()

